# Generated by Django 3.2.15 on 2022-09-03 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_rename_ratings_product_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(related_name='products', through='products.Rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
